### ISSUE TITLE
[ERROR] You must pass a directory path string

### ISSUE THREAD

**Issue by brunowego** [metalsmith/metalsmith#230]
I am having some difficulty in putting to work metalsmith in my architecture. I have no idea where I am going wrong, a help here would be incredible!

**tasks/pages.js**

```js
import config from '../config';

import gulp from 'gulp';
import metalsmith from 'metalsmith';
import markdown from 'metalsmith-markdown';
import layouts from 'metalsmith-layouts';

gulp.task('pages', () => {
  gulp.src(config.pages.src)
    .pipe(metalsmith({
      use: [
        markdown(),
        layouts({
          engine: 'swig',
          directory: 'docs/layouts',
        }),
      ],
    }))
    .pipe(gulp.dest(config.pages.dest));
});
```

**configs/pages.js**

```js
import paths from '../paths';

export default {
  dest: paths.docs,
  src: paths.docs + paths.pages + '/*.md',
  watch: [paths.docs + paths.pages + '/*.md'],
};
```

**Console Output**

```bash
[09:45:42] Requiring external module babel-register
[09:45:43] Using gulpfile ~/[Secret]/gulpfile.babel.js
[09:45:43] Starting 'pages'...
[09:45:43] 'pages' errored after 8.1 ms
[09:45:43] AssertionError: You must pass a directory path string.
    at Metalsmith.directory (/Users/Bruno/[Secret]/node_modules/metalsmith/lib/index.js:71:3)
    at new Metalsmith (/Users/Bruno/[Secret]/node_modules/metalsmith/lib/index.js:41:8)
    at Metalsmith (/Users/Bruno/[Secret]/node_modules/metalsmith/lib/index.js:37:45)
    at Gulp.<anonymous> (pages.js:10:11)
    at module.exports (/Users/Bruno/[Secret]/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/Bruno/[Secret]/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/Bruno/[Secret]/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/Bruno/[Secret]/node_modules/orchestrator/index.js:134:8)
    at /Users/Bruno/.nvm/versions/node/v5.4.1/lib/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
    at Function.Module.runMain (module.js:431:11)
    at startup (node.js:139:18)
    at node.js:999:3
[tyker]
```

**Comment by Ajedi32** [comment]
Metalsmith isn't a Gulp plugin. Perhaps you're looking for [gulpsmith](https://github.com/pjeby/gulpsmith) or [gulp-metalsmith](https://github.com/jelz/gulp-metalsmith).

**Comment by brunowego** [comment]
@Ajedi32, yes with gulp-metalsmith works, I had tried before. I was willing to use directly metalsmith. Thanks!
