### ISSUE TITLE
Including metalsmith breaks Travis CI build

### ISSUE THREAD

**Issue by barrymcgee** [metalsmith/metalsmith#241]
Adding metalsmith to my build chain breaks my Travis build, giving the following error;

```js
$ node_modules/gulp/bin/gulp.js build
/home/travis/build/ubuntudesign/vanilla-framework/node_modules/metalsmith/lib/index.js:190
Metalsmith.prototype.build = unyield(function*(){
                                             ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/ubuntudesign/vanilla-framework/node_modules/metalsmith/index.js:6:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/ubuntudesign/vanilla-framework/gulpfile.js:48:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
The command "node_modules/gulp/bin/gulp.js build" failed and exited with 8 during .
``` 

Am I correct to assume this points to a linting error within Metalsmith?

**Comment by davidosomething** [comment]
Make sure you're using a modern version of node js or adding async support to node on your travis image
Be default I think travis still uses node 0.12

```
nvm install 6
```

**Comment by woodyrew** [comment]
Not a linting error. This will be on Node version < 0.12 - No generator support.

Alternative is to use Metalsmith `v1.7.x` as per [Troubleshooting](https://github.com/metalsmith/metalsmith#troubleshooting)

**Comment by barrymcgee** [comment]
Thank you both!
